config/routes.rb
Rails.application.routes.draw do

    # routes!
    get 'log_in' => 'sessions#new', :as => 'log_in'
    get 'sign_up' => 'users#new', :as => 'sign_up'
    get 'log_out' => 'sessions#destroy', :as => 'log_out'

    # resources!
    resources :posts do
        resources :comments, :except => [:edit, :update]
    end
    resources :users, :except => [:index, :destroy]
    resources :sessions, :only => [:new, :create, :destroy]

    # root '/' path!
    root :to => 'welcome#index'
end

app/models/comment.rb
class Comment < Rfm::Base
  config :layout=>'Comments',
         :field_mapping => { 'idPost' => 'id_post',
                             'idUser' => 'id_user',
                             'CreationTimestamp' => 'creation_time',
                             'Body' => 'body',
                             'users_POSTS_comments_USER::DisplayName' => 'display_name'}

end

app/models/post.rb
class Post < Rfm::Base
  attr_accessor :comments

  config :layout=>'AllPosts',
         :field_mapping => {'id' => 'id',
             'Title' => 'title',
             'Body' => 'body',
             'creationTimestamp' => 'creation_time',
             'idUser' => 'id_user',
             'Users::DisplayName' => 'display_name'}
  validates :title, length: {minimum: 2}
  validates :body, length: {minimum: 5}

end

app/models/user.rb
class User < Rfm::Base
    attr_accessor :password, :hidden

    before_create :encrypt_password

    config :layout=>'Users',
           :field_mapping => {'PasswordHash' => 'password_hash',
             'PasswordSalt' => 'password_salt',
             'EmailAddress' => 'email',
             'DisplayName' => 'display_name'}
    validates :email, length: {minimum: 6}
    validates :display_name, length: {minimum: 2}
    validates :password, length: {minimum: 6}
    validates :hidden, numericality: { equal_to: 3}

    # Authenticate a user
    def self.authenticate(email, password)
      # Include the == when searching for exact match because filemaker
      user = User.find(:email => '==' + email).first
      puts email
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        puts 'user authenticated'
        user
      else
        puts 'user not authenticated'
        nil
      end
    end

    # Hash the provided password for storings
    def encrypt_password
      if password.present?
        puts 'password is present'
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def check_logged_in
    logger.info 'checking if user is logged in'
    if session[:user_id]
      true
    else
      redirect_to posts_path, notice: 'You must be logged in'
    end
  end

  # Check that the current use is authorized to access this content
  def authorize(id, redirect_path)
    logger.info 'checking user id'
    if session[:user_id] == id
      true
    else
      redirect_to redirect_path, notice: 'You do not have access to modify this content'
    end

  end

  private
  # Gets the current user by the session's user id if it exists
    def current_user
      @current_user ||= User.find(:id => session[:user_id]).first if session[:user_id]
    end
end

app/controllers/comments_controller.rb
require 'securerandom'

class CommentsController < ApplicationController
  before_action :check_logged_in, except: [:index, :show]

  def index
    @comments = Comment.find({:id => '*'}, :sort_field => :creation_time)
  end

  def show
    @comment = Comment.find(:id => params[:id]).first
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(:id => params[:id]).first
  end

  def create
    begin
      @comment = Comment.new(:body => post_params[:body])
      @comment.id = SecureRandom.uuid
      @comment.id_post = params[:post_id]
      @comment.id_user = session[:user_id]

      @comment.save!
      redirect_to posts_path
    rescue RuntimeError
      render 'edit'
    end
  end

  def update
  end

  def destroy
    @commment = Comment.find(:id => params[:id]).first

    @comment.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
require 'securerandom'

class PostsController < ApplicationController
  # TODO Refactor to using a repositories!
  # Require a logged in user for everything except ...
  before_action :check_logged_in, except: [:index, :show]

  def index
    @posts = Post.find({:id => '*'}, :sort_field => :creation_time, :sort_order => :descend)
  end

  def show
    @post = Post.find(:id => params[:id]).first
    # @post = Repository.for(:post).find_by_id(params[:id])
    # Get comments for this post
    @post.comments = Comment.find({:id_post => @post.id}, :sort_field => :creation_time, :sort_order => :descend, :max_records => 20)
    @post
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find({:id => params[:id]}).first
    authorize(@post.id_user, post_path)
    @post
  end

  def create
    # FFFFFFFFF y no pparams passsing wtf
    begin
      @post = Post.new :title => post_params[:title], :body => post_params[:body]
      @post.id = SecureRandom.uuid
      @post.id_user = session[:user_id]

      @post.save!
      redirect_to posts_path
    rescue RuntimeError
      render 'new'
    end
  end

  def update
    @post = Post.find(:id => params[:id]).first
    authorize(@post.id_user, post_path)

    if @post.update_attributes!(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(:id => params[:id]).first
    authorize(@post.id_user, post_path)

    # Need to delete any comments as well
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    # Log in with the provided credentials
    def create
        user = User.authenticate(params[:email], params[:password])
        if user
            session[:user_id] = user.id
            redirect_to root_url
        else
            flash.now.alert = 'Invalid username/password'
            render 'new'
        end
    end

    # Logout by removing the user id stored in the session
    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
require 'securerandom'

class UsersController < ApplicationController
  before_action :check_logged_in, only: [:edit, :update]

  def new
    @user = User.new
  end

  def edit
    @user = User.find(:id => params[:id]).first
    authorize(@user.id, root_path)
  end

  def create
    # TODO Add password confirmation
    # TODO Refactor everything!
    # Checks for existing user with this email
    @user = User.find(:email => '==' + post_params[:email]).first
    if @user
      @user.errors.add(:base, 'A user already exists with this email address')
      render 'new' and return
    end
    @user = User.new(:email => post_params[:email], :display_name => post_params[:display_name], :password => post_params[:password], :hidden => post_params[:hidden])
    @user.id = SecureRandom.uuid
    logger.info @user
    begin
      @user.save!
      redirect_to root_path
    rescue RuntimeError
      render 'new'
    end
  end

  def update
    # TODO Set up editing of passwords, and whatever other fields should exist
    @user = User.find(:id => params[:id]).first
    authorize(@user.id, root_path)

    begin
      # This is so because the rfm OIMSDOIDSCDM calls its save with validation from its save without validation. i should just change it.
      @user.update_attributes(:email => post_params[:email], :display_name => post_params[:display_name], :password => 'random', :hidden => 3)
      # Skip validation since we don't have the password
      @user.save
      redirect_to root_path, notice: 'Your information has been updated!'
    rescue
      logger.info 'wht the fuck'
      render 'edit'
    end


  end

  private
    def post_params
      params.require(:user).permit(:email, :display_name, :password, :hidden)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_for_user
    true
  end

  # Formats filemaker timestamps into something more presentable
  def format_date(date)
    date.strftime('%x %r')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/edit.slim
h1 Comments#edit
p Find me in app/views/comments/edit.slim

app/views/comments/new.slim
h3 New Comment

= form_for @comment, url: post_comments_path do |f|
  - if @comment.errors.any?
    div.alert.alert-warning
      h2
        = pluralize(@comment.errors.count, 'error') + ' prohibited this post from being saved:'
      ul
        - @comment.errors.full_messages.each do |msg|
          li = msg

  div.form-group
    = f.label :body
    br
    .col-sm-6
      = f.text_area :body, class: 'form-control'
  .col-sm-10
    = f.submit 'Save', class: 'btn btn-primary'

app/views/comments/show.slim
h1 Comments#show
p Find me in app/views/comments/show.slim

app/views/comments/update.slim
h1 Comments#update
p Find me in app/views/comments/update.slim

app/views/layouts/_footer.slim
div.row
  h5 asdf

app/views/layouts/_navbar.slim
nav.navbar.navbar-toggleable-md.navbar-light.navbar-inverse.bg-inverse
  div.container
    button.navbar-toggler.navbar-toggler-right type='button' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'
      span.navbar-toggler-icon
    a = link_to 'railsBLog!', root_path, class: 'navbar-brand'
    div#navbar.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          a = link_to 'Home', root_path, class: 'nav-link'
        li.nav-item
          a = link_to 'Posts', posts_path, class: 'nav-link'
        li.nav-item
          a.nav-link href='https://bitbucket.org/gitmag/fm_blog' Source
      ul.navbar-nav.navbar-right
        - if current_user
          li.nav-item
            a = link_to 'Edit Account', edit_user_path(current_user.id), class: 'nav-link'
          li.nav-item
            a = link_to 'Logout', log_out_path, class: 'nav-link'
        - else
          li.nav-item
            a = link_to 'Sign Up', sign_up_path, class: 'nav-link'
          li.nav-item
            a = link_to 'Login', log_in_path, class: 'nav-link'

app/views/layouts/application.slim
doctype html
html
  head
      title Rails blogging!
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      = csrf_meta_tags
  body
    = render 'layouts/navbar'

    div.container
      - if flash[:notice]
        .alert.alert-warning
          = flash[:notice]
      == yield

app/views/posts/_edit_form.slim
= form_for post do |f|
  - if post.errors.any?
    div.error_explanation
      h2
        = pluralize(post.errors.count, "error") + " prohibited this post from being saved:"
      ul
        - post.errors.full_messages.each do |msg|
          li = msg

  div.form-group
    = f.label :title
    br
    .col-sm-6
      = f.text_field :title, class: 'form-control'
  div.form-group
    = f.label :body
    br
    .col-sm-6
      = f.text_area :body, class: 'form-control'
  .col-sm-10
    = f.submit 'asdf', class: 'btn btn-primary'

app/views/posts/edit.slim
h3 Edit Post

= form_for @post, url: post_path do |f|
  - if @post.errors.any?
    div.alert.alert-warning
      h2
        = pluralize(@post.errors.count, 'errpr') + ' prohibited this post from being saved:'
      ul
        - @post.errors.full_messages.each do |msg|
          li = msg

  div.form-group
    = f.label :title
    br
    .col-sm-6
      = f.text_field :title, class: 'form-control'
  div.form-group
    = f.label :body
    br
    .col-sm-6
      = f.text_area :body, class: 'form-control'
  .col-sm-10
    = f.submit 'Save', class: 'btn btn-primary'

app/views/posts/index.slim
table.table
  thead
    tr
      th Title
      th Poster
      th Post Time
  tbody
    - @posts.each do |post|
      tr
        td == link_to post.title, post_path(:id => post.id)
        - if post.display_name
          td = post.display_name
        - else
          td
        - if post.creation_time
          td = format_date(post.creation_time)
== link_to 'New Post', new_post_path, :class => 'btn btn-primary'

app/views/posts/new.slim
h3 New Post

= form_for @post, url: posts_path do |f|
  - if @post.errors.any?
    div.alert.alert-warning
      h2
        = pluralize(@post.errors.count, "error") + " prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |msg|
          li = msg

  div.form-group
    = f.label :title
    br
    .col-sm-8
      = f.text_field :title, class: 'form-control'
  div.form-group
    = f.label :body
    br
    .col-sm-8
      = f.text_area :body, class: 'form-control'
  .col-sm-10
    = f.submit 'Save', class: 'btn btn-primary'

app/views/posts/show.slim
div.card
  h3.card-header
    = @post.title
    .float-right.h5
      = format_date(@post.creation_time)
  div.card-block
    h6.card-subtitle.mb-2.text-muted
      | By:
      = @post.display_name
    p.card-text
      = simple_format(@post.body)
    - if current_user && current_user.id == @post.id_user
      br
      .btn-toolbar
        == link_to 'Edit', edit_post_path(@post), :class => 'btn btn-info'
        == link_to 'Delete', post_path(@post), data: {:confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-primary'
br
- if current_user
  == link_to 'Add Comment', new_post_comment_path(:post_id => @post.id), :class => 'btn btn-primary'
br
- if @post.comments.any?
  div.row.justify-content-center
    div.col-8
      h3 Comments
      - @post.comments.each do |comment|
        div.card
          div.card-block
            p.card-text
              = simple_format(comment.body)
          div.card-footer
            | By:
            = comment.display_name
            .float-right
              = format_date(comment.creation_time)
        br

app/views/users/_edit_form.slim
= form_for :user, html: { class: 'form'}, url: users_path do |f|
  - if @user.errors.any?
    div.alert.alert-warning
      h2
        = pluralize(@user.errors.count, 'error') + ' prohibited this user from being created:'
      ul
        - @user.errors.full_messages.each do |msg|
          li = msg

  div.form-group
    = f.label :email
    br
    .col-sm-4
      = f.text_field :email, class: 'form-control', oninput: 'set_hidden()'
  div.form-group
    =f.label :display_name
    br
    .col-sm-4
      = f.text_field :display_name, class: 'form-control'
  div.form-group
    = f.label :password
    br
    .col-sm-4
      = f.password_field :password,  class: 'form-control'
  div.form-group
    = f.hidden_field :hidden, class: 'form-control'
  .col-sm-10
    = f.submit 'Create', class: 'btn btn-primary'

/ Set a hidden field on input to deter bots maybe
javascript:
  function set_hidden() {
    document.getElementById('user_hidden').value='3';
  }

app/views/users/edit.slim
h3 Edit your information!

= form_for @user, html: { class: 'form'}, url: user_path do |f|
  - if @user.errors.any?
    div.alert.alert-warning
      h2
        = pluralize(@user.errors.count, 'error') + ' prohibited this user from being created:'
      ul
        - @user.errors.full_messages.each do |msg|
          li = msg

  div.form-group
    =f. label :email
    .col-sm-4
      = f.text_field :email, :readonly => true, class: 'form-control'
  div.form-group
    =f.label :display_name
    .col-sm-4
      = f.text_field :display_name, class: 'form-control'
  .col-sm-10
    = f.submit 'Save', class: 'btn btn-primary'

app/views/users/new.slim
h3 Create New User

= render 'users/edit_form'

app/views/welcome/index.slim
div.container
  p
    | This is mainly a website to use ruby/rails and integrate with a Filemaker database. It is
      a blogging platform with support for comments, and requiring registered users for anything that
      involves CRUD. It uses the RFM gem from ginjo for Filemaker interaction and a DIY implementation
      of authentication.

  p
    | Ideally, Filemaker will do exactly nothing besides store data. Any domain/business rules will exist
      in ruby. And so at some point something like the repositories pattern will be implemented to
      make it easy to move to some other database/storage mechanism.